language: node_js

node_js:
  - "node"

os:
  - linux

branches:
  only:
  - master

script: node ./build.js

after_success:
  - source ./push_list.sh

env:
  global:
    secure: jdMxLqnAuAWL9tJTsQxOIWmuWUVyes8TE7Trlxkps7sa58fKBWaUfrf1x8odvZBlSHnKW8W/xje/Nou5OSgHHch5B9tRQ6Y4kqymp09LLeaRw8Dpxo3valqcWcF0mi84BcjAUZwPNrN3v6dn06yjI0+27asVjuV5rS/VR9z/yjTMkNLGP1/F4FNBGKypY8+JVx1Ql2C54VEQWx0+z9oKpLvZZ+rHPIBUHFJXjR2Liflni+8WHQmZV4IhdxvP46RH8UnDLNUagK3PTSqa8eBJkaufvRGdIclr56kMOc1ZMCnEPd6qWasp3RihUgs5jyPidg56nwHH2aHVVfyvvkrOQGLKyreyJuf0v/Iyxegc3MHUKL/V0Puy3uunVCf4NuOq/CoRVGNzx1KR/ntl+pbRKVDfSwKM5rGE4Ig7nb33S+ZJRwEXQQZp0Tcg0fVBPJ27ZEduQw/DqoU6qJbXkfmIzGzemmLcqcVkTWyREqx7SaVna7KZs4rkqpuMT63KBcOaUvRoeC5KnXJK57G7XbSDBzTxn5+cJOHb8PZfbBST5BYGi9hRh/5kQxfhsyaw2PYUHKdDmg9+k+O55fPq+8CBWNHOe5krZe9zQYdV3OTZV9/9JXaH2IIwkNc3oaUKK19ssxZkwN9ohPQKheWduKTkUgOjz/CHbDaVQYPAMpiTq4U=